backend:
 name: git-gateway
 branch: main

media_folder: _site/cats
public_folder: /cats

collections:
- name: "blog"
  label: "Blog"
  label_singular: "Post"
  folder: "_site/posts"
  create: true
  fields:
   - { label: "Title", name: "title", widget: "string" }
   - { label: "Publish Date", name: "date", widget: "datetime" }
   - { label: "Body", name: "body", widget: "markdown" }